### ISSUE TITLE
kart.finn.no [Incorrect blocking]

### ISSUE THREAD

**Issue by Alex-302** [adblock-thai/thai-ads-filter#13]
### Issue URL (Incorrect Blocking)
 [https://kart.finn.no/?finnkode=188382064&lat=59.90883&lng=10.856678&mapType=finnvector&showPin=1&bl=1](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fkart.finn.no%2F%3Ffinnkode%3D188382064%26lat%3D59.90883%26lng%3D10.856678%26mapType%3Dfinnvector%26showPin%3D1%26bl%3D1)
### Comment
> 

Caused by `##.banner`

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/DKaq3AS.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/6Ok3WHa.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.5.12
Browser: | Chrome
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Other:</b><br/> Filter unblocking search ads and self-promotion<br/><br/><b>Language-specific:</b><br/> AdGuard German, <br/>AdGuard Spanish/Portuguese, <br/>Liste AR, <br/>Thai Ads Filters, <br/>Frellwit's Swedish Filter, <br/>Dandelion Sprout's Nordic Filters

**Comment by pakonda** [comment]
@all-contributors please add @Alex-302 for bug
