### ISSUE TITLE
pi hole ด้วยได้ไหมครับ

### ISSUE THREAD

**Issue by lambogreny** [adblock-thai/thai-ads-filter#6]
pi hole ด้วยได้ไหมครับ

**Comment by pakonda** [comment]
> pi hole ด้วยได้ไหมครับ

pihole แนะนำของคุณ @kowith337 ครับ
https://github.com/kowith337/CustomHosts-via-hostsmgr

**Comment by kowith337** [comment]
ส่วนตัวไม่อยากแนะนำให้ใช้ Hosts File ของผมเท่าไหร่ครับ เพราะมันบล็อกบางเว็บที่หลายคนอาจจะจำเป็น อย่างเช่น
- `h.facebook.com`, `mobile.facebook.com`, `web.facebook.com` เนื่องจากเป็น Subdomain ของ Facebook ที่เกี่ยพันกับ `Free Basics`
- `l.facebook.com`, `lm.facebook.com` บล็อกไม่ให้คลิกลิงค์ภายนอกใดๆ ที่โพสใน Facebook เป็นต้น

แนะนำให้ลองใช้จาก https://github.com/deathbybandaid/piholeparser ดูก่อนครับ
- https://github.com/deathbybandaid/piholeparser/raw/master/Subscribable-Lists/CountryCodesLists/Thailand.txt
- https://github.com/deathbybandaid/piholeparser/raw/master/Subscribable-Lists/ParsedBlacklists/EasyList-Thailand.txt
