### ISSUE TITLE
||edgesuite.net blocked "play.itunes.apple.com.edgesuite.net"

### ISSUE THREAD

**Issue by hezhijie0327** [adblock-thai/thai-ads-filter#8]
Environment: AdGuard Home

Blocked by CNAME or IP in response
CNAME: play-cdn.itunes-apple.com.akadns.net. (ttl=2323)
CNAME: play.itunes.apple.com.edgesuite.net. (ttl=2323)
CNAME: a1806.dscb.akamai.net. (ttl=192)
AAAA: 2600:1406:3::b81c:bcc2 (ttl=8)
AAAA: 2600:1406:3::b81c:bcc3 (ttl=8)

**Comment by hezhijie0327** [comment]
"edgesuite.net" is a CDN provider. Many companies use it, such as Apple, Steam, letsencrypt.org, etc. If you use the rule like the one "||edgesuite.net" which existed in current rule list, it may occurred many connectivity issues. It not only blocked "edgesuite.net", but also blocked all the sub-domains. I really hope that the issue could be fixed as quick as possible, thanks very much.

// Solutions:
1. Delete or change it as followed
@@||edgesuite.net^

2. Block its sub-domain instead of block its main-domain
||ads.edgesuite.net^

// Known issues:
ax.itunes.apple.com
init.ess.apple.com
init-p01md.apple.com
isrg.trustid.ocsp.identrust.com
steamcdn-a.akamaihd.net
ocsp.int-x3.letsencrypt.org

**Comment by kowith337** [comment]
Some ad company use it (e.g. `YieldManager`), but the blocking rules are start from my filters named **ThaiParanoidBlock** may transfered here because this focused to block Thai ads and trackings.

I have no idea if any known good companies are use that `EdgeSuite` CDN, but for me, rarely to see who use that but mostly it's used as abusive way, can you prove more evidences?

**Comment by hezhijie0327** [comment]
play.itunes.apple.com.edgesuite.net --> Apple Music (Music Play / Download)
officecdn.microsoft.com.edgesuite.net --> Microsoft Office (Download / Update)
steamcdn-a.akamaihd.net.edgesuite.net --> Steam (Game Download)
ocsp.int-x3.letsencrypt.org.edgesuite.net --> Let's Encrypt (SSL/TLS Certificate)

I don’t think it ’s wise to block all of them. If YieldManager uses it as an advertising service, it should add rules for it instead of blocking both normal and abnormal. For example: 
||ad.yieldmanager.com^
or may be it use EdgeSuite CDN (Possible)
||ad.yieldmanager.com.edgesuite.net^

**Comment by Alex-302** [comment]
Yep. Better block specific sub-domains.

**Comment by kowith337** [comment]
Whitelist entirely isn't a good idea, and this filter mainly aim to apply in uBlockOrigin or NanoAdBlocker, use with other tools may not recommended.

Instead of whitelisting, maybe just remove out from this blocking list but let another filter lists handle it?

**Comment by hezhijie0327** [comment]
😊

**Comment by Alex-302** [comment]
Thanks
